dbt/adapters/dremio/__version__.py
pyproject.toml
setup.py

Required the "b" to be dropped in the versionso that it would be installed by PyPi.
Added toml file as required by twine.

Updates to support upload distribution to PyPI

---

dbt/adapters/dremio/api/basic.py
tests/functional/adapter/test_basic.py

When running the tests consecutively, the login endpoint is hit too many times, resulting in a connection error. To resolve this we've added a delay between the tests.
Added a fixture that's autoused by the tests to sleep 1 second in between each tests.
https://github.com/dremio/dbt-dremio/issues/22
@jlarue26 
@argusli

Resolve hitting endpoint too many times

---

dbt/include/dremio/macros/adapters/metadata.sql
dbt/include/dremio/macros/materializations/reflection/reflection.sql

Make dremio:reflections_enabled default to false if not declared.
dremio:reflections_enabled will now default to false. We expect most users to have accounts without admin privileges. Since listing reflections requires admin privileges, the default should be to disable reflections, with admins having to enable them if needed.
#18 
@jlarue26 @ravjotbrar

Make dremio:reflections_enabled default to false if not declared.

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
dbt/include/dremio/macros/utils/data_types.sql
tests/functional/adapter/grants/test_snapshot_grants.py

Fix type_string return string instead of varchar
`dremio__type_string()` macro overrides the dbt-core `default__type_string()` macro to use the Dremio supported VARCHAR instead of the default string.
Modified tests/functional/adapter/grants/test_snapshot_grants.py to test the `dremio__type_string()` macro.
my_snapshot_sql previously overwrote `type_string()` with just "VARCHAR". Reverted back to use `type_string()` macro.
https://github.com/dremio/dbt-dremio/issues/78

Fix type_string returning string instead of varchar

---

CHANGELOG.md
dbt/adapters/dremio/api/cursor.py

Update _populate_job_results pagination limit to be 500
Change __populate_job_results()'s call of job_results() to have a limit of 500, which is Dremio's limit. Part 1 of the fix, with part 2 being implementing pagination.
Ran all of the tests using software, with them all passing apart from a known failure in tests/functional/adapter/grants/test_model_grants.py.
https://github.com/dremio/dbt-dremio/issues/61

Update _populate_job_results pagination limit to be 500

---

CHANGELOG.md
dbt/adapters/dremio/api/cursor.py
tests/unit/test_job_results.py

Implement job results pagination
- Add optional row_limit argument to _populate_job_results().
- Set row_limit default to 100.
- Create test_job_result.py unit test that tests pagination.
softwareUP --> PASS
softwarePAT --> PASS
Resolves #61

Implement job results pagination

---

CHANGELOG.md
dbt/adapters/dremio/api/cursor.py
tests/functional/adapter/grants/test_invalid_grants.py
tests/unit/test_job_results.py
tests/unit/test_payload_error.py

Prior to this change, we were not checking to see of a job is in a FAILED state. Instead, we would attempt to get job_results for every job, which would return an error about not being able to get results of a job in a failed state. Now we check to see if the job failed and return the error message in the payload.
In cursor.py:
```
if job_status_state == "FAILED":
error_message = job_status_response["errorMessage"]
raise Exception(f"ERROR: {error_message}")
```
tests/unit/test_connection.py .                                                               [ 50%]
tests/unit/test_payload_error.py .                                                            [100%]
================================= 2 passed in 1.08s =================================== …

Get the actual error message from Dremio

---

CHANGELOG.md
THIRD_PARTY_LICENSES.txt
dbt/adapters/dremio/__version__.py
dbt/adapters/dremio/relation.py
dev_requirements.txt
setup.py
tests/functional/adapter/query_comment/test_query_comment.py

Implemented the query comment tests specified by dbt, upgraded to python 3.11, and changed our adapter version to 1.4.1
- Included all query comment tests specified by dbt
- Imported our fixtures to deal with object_storage_path issue
- Use a default_factory to match how dbt-core instantiates the includepolicy and quotepolicy
- Changed all instances of our adapter version to match dbt-core 1.4.1
```
ravjotb@RavjotsMacBookPro dbt-dremio % pytest tests/functional/adapter/query_comment | tee ../output.txt
============================= test session starts ==============================
collected 6 items
tests/functional/adapter/query_comment/test_query_comment.py ......      [100%]
======================= 6 passed, 12 warnings in 41.61s ========================
```
``` …
```

Implement Query Comment Tests

---

CHANGELOG.md
tests/functional/adapter/relation/test_changing_relation_type.py

implement test_changing_relation_types test
No modifications (other than the object_storage stuff) required for the test to work.
Ran all functional tests -> Passed
https://github.com/dremio/dbt-dremio/issues/117

implement test_changing_relation_types test

---

CHANGELOG.md
dbt/adapters/dremio/connections.py
tests/functional/adapter/utils/test_timestamps.py

Implement base current timestamps test
Overwrote the test to work with Dremio syntax. Dremio only has one timestamp type, so we implemented this test similar to many other adapters. 
Only ran the TestCurrentTimestampDremio test that was implemeneted in test_timestamps.py. No other functionality was altered, so no other tests were ran. 
https://github.com/dremio/dbt-dremio/issues/117

Implement base current timestamps test

---

CHANGELOG.md
dbt/include/dremio/dbt_project.yml
dbt/include/dremio/macros/adapters/metadata.sql

Performance Enhancement for information schematables
- Create a new variable `dremio:exact_search_enabled` which defaults to false
- If variable set to true, changes the ilike to a basic equality for the `dremio__list_relations_without_caching` macro when reflections are disabled (which is the default)
Thanks @ravjotbrar for running the test suite with the variable not set (which is the default).
All tests pass.

134 performance enhancement for information schematables

---

dbt/include/dremio/macros/materializations/incremental/incremental.sql
tests/functional/adapter/dremio_specific/test_drop_temp_table.py

In our latest release, we made changes to standardize incremental materializations. However, since Dremio does not support temporary tables directly, the temporary tables created when dealing with incremental materializations were persisting in the object storage source.
Added the __dbt_tmp table to the list of tables to drop in the incremental.sql macro. Also, implemented a test to ensure the tables are being dropped. 
Ran all functional tests -> pass
-   [ ] Added a summary of what this PR accomplishes to CHANGELOG.md
https://github.com/dremio/dbt-dremio/issues/136

Ensure temp tables don't persist in source

---

tests/component/test_profile_template.py

Remove test case for `verify_ssl` option.
The `verify_ssl` option was removed from the interactive profile creation, but the test wasn't updated to check for it.
Ran `test_profile_template.py`. Test now passes.
Not really necessary.
None.

Remove test case for verify_ssl that was missed in previous PR

---

dbt/adapters/dremio/api/cursor.py
dbt/adapters/dremio/connections.py
tests/hooks/test_model_hooks.py

Before this change, execution time was idling even after the job was finished in Dremio. This was happening because the adapter would fetch unnecessary data from the materialized model. 
This change makes it so the adapter only fetches data from the materialized model if fetch is set to true. 
All tests pass
https://github.com/dremio/dbt-dremio/issues/176

Make fetch configurable and fix hook tests

---

CHANGELOG.md
dbt/adapters/dremio/relation.py
tests/functional/adapter/dremio_specific/test_schema_parsing.py

Prior to this change, users would not be able to specify a schema with a dot in it. For instance, schema.parse would get quoted as "schema"."parse", even though the user intended to quote the entire identifier. Now users can choose to wrap the schema in single quotes and add double quotes around the parts they want. 
Add regex to match a pattern containing quotes. Solution provided by @dremio-brock. 
All tests pass.
https://github.com/dremio/dbt-dremio/issues/203

Fix schema parsing

---

dbt/include/dremio/macros/builtins/builtins.sql

Add optional named parameter to macro ref.
To use model versions with dbt (https://docs.getdbt.com/docs/collaborate/govern/model-versions#how-is-this-different-from-just-creating-a-new-model) it is necessary to have a optional parameter v in the ref macro.
I tested it locally on our dremio installation
-   [ ] Added optional parameter v to the ref macro

Add version v to macro ref

---

dbt/adapters/dremio/api/cursor.py
dbt/adapters/dremio/connections.py
dbt/include/dremio/macros/materializations/incremental/incremental.sql
dbt/include/dremio/macros/materializations/reflection/reflection.sql

During the second run of an incremental materialization, the adapter would try and fetch records from the temporary table it is creating. This made the adapter hang if the table was large enough. 
Made the fetch configuration false by default. Also changed the run_query macro to use call_statement, as run_query will always fetch the data that is returned by the sql query. Thanks to @mxmarg for the initial iteration of this fix. 
https://github.com/dremio/dbt-dremio/issues/211

Ensure adapter does not fetch actual records from materialization

---

dbt/include/dremio/macros/adapters/format.sql
setup.py

See https://github.com/dremio/dbt-dremio/issues/208 for a summary of the issue.
The fix involved adding iceberg as a format option when creating tables. Additionally, I changed the version to prepare for a minor release including these fixes.

Add iceberg as table type in format

---

CHANGELOG.md
README.md
THIRD_PARTY_LICENSES.txt
dbt/adapters/dremio/__version__.py
dbt/adapters/dremio/relation.py

We made changes to the schema parsing that allowed for schemas that contained dots. However, this requires users to specify ALL schemas wrapped in single quotes and then double quotes (`'"my_schema"'`), otherwise it won't add any quotes to schemas. With this change users can continue to add their schema as normal (`'my_schema'`).
Added a condition to check if double quotes are contained in the schema definition. If so, we use the most recent logic. If not we use the regular logic. 
-   [ ] Added a summary of what this PR accomplishes to CHANGELOG.md

Make schema parsing backwards compatible

---

CHANGELOG.md
dbt/adapters/dremio/api/cursor.py
dbt/adapters/dremio/api/rest/endpoints.py

The cursor implementation was using `while True` loop to poll for result from REST API of Dremio. Without throttling, it will jam the server easily, especially when using a high number of thread count. Since most SQL jobs need a few second to run, looping too fast to get the result is unessesary.
Also, in REST client implementation, using `get`, `post`, `delete` directly from `requests` is inefficient because it will create new HTTP session with the server everytime the polling is called.
1. Use `request.Session` instead of vanila `requests` to utilize connection pooling, so optimize networking performance
2. Add `time.sleep` in `while True` loop to slow down the polling

Optimize REST API workload by using Session and slowing down polling loop

---

CHANGELOG.md
dbt/include/dremio/macros/materializations/incremental/incremental.sql
dbt/include/dremio/macros/materializations/incremental/strategies.sql
dbt/include/dremio/macros/materializations/incremental/validate.sql
tests/functional/adapter/basic/test_incremental.py

Add implementation for merge functionality when using an incremental materialization. 
Dremio supports both merge and append now. More details on how to use merge strategies can be found here: https://docs.getdbt.com/docs/build/incremental-strategy#strategy-specific-configs. 
Only ran incremental tests as the new changes don't impact other parts of the adapter. 
(https://github.com/dremio/dbt-dremio/issues/224)

Add Incremental Merge Strategy

---

CHANGELOG.md
dbt/include/dremio/macros/adapters/metadata.sql
tests/functional/adapter/relation/test_get_relation_last_modified.py

Metadata freshness checks were not working properly if `dbt source freshness` was ran without using the `loaded_at_field` keyword. This is because we were not reducing the amount of results to the max commited_at value in our metadata select statement.
Added the max operator as suggested by @KingLommel. Also fixed the relevant test to include more than one snapshot. 
https://github.com/dremio/dbt-dremio/issues/229

Add max operator to get_relation_last_modified macro

---

dbt/include/dremio/macros/materializations/incremental/strategies.sql

Added fix for #242 
Append DBT_INTERNAL_SOURCE to all columns in the values statement generated by the macro `dremio__get_incremental_merge_sql`
The example provided in the issue now works seamlessly
-   [ ] Added a summary of what this PR accomplishes to CHANGELOG.md
#242

Fix incremental merge strategy

---

.github/scripts/clean_pycache.sh
.github/scripts/create_dbt_projects.sh
.github/scripts/create_dbt_test_users.sh
.github/scripts/create_docker_network.sh
.github/scripts/create_dremio_s3_source.sh
.github/scripts/create_env_file.sh
.github/scripts/create_minio_bucket.sh
.github/scripts/install_minio_client.sh
.github/scripts/run_tests.sh
.github/scripts/start_dremio.sh
.github/scripts/start_minio.sh
.github/workflows/ci.yml

Made some improvements to our CI workflow
- Broke down the steps in the pipeline into different bash scripts for readability and local reproducibility
- Setting environment variables using the correct approach for action jobs
- Credentials (even dummy) handled through secrets
N/A
- Created scripts inside `.github/scripts`
- Updated `.github/ci.yml`
https://github.com/dremio/dbt-dremio/issues/39
This improves https://github.com/dremio/dbt-dremio/pull/248

Improve the CI workflow

---

.github/workflows/ci.yml

Removed the need for secrets usage
Removed the usage of secrets since they are not passed to workflows that are triggered by a pull request from a fork
These are dummy values since we setup and deploy instances locally in the pipeline itself
N/A
- moved dummy values out of secrets in `.github/workflows/ci.yml`
N/A

Remove secrets and use dummy values

---

CHANGELOG.md
dbt/adapters/dremio/api/rest/client.py
dbt/adapters/dremio/api/rest/url_builder.py
dbt/adapters/dremio/connections.py
dbt/adapters/dremio/impl.py
dbt/include/dremio/macros/adapters/persist_docs.sql
dbt/include/dremio/macros/materializations/view/view.sql
tests/functional/adapter/dremio_specific/test_persist_docs.py

Wikis and tags feature implementation.
One of dbt's core features is source documentation. Right now, this documentation does not propagate into Dremio’s wiki, leading to two separate sources of truth.
The goal is to display dbt documentation - more specifically, wikis and tags - inside of Dremio.
All added tests are running
- Added tests to check wikis and tags creation for table models
- Added tests to check wikis and tags creation, update and deletion for view models
- Possibility to integrate wikis and tags by enabling `relation` option from `persist_docs` configuration
- New macro `dremio__persist_docs` created
- Views also perform `persist_docs` macro
- Integration via REST API
#86 
#196

Implementation of wikis and tags feature

---

.github/workflows/ci.yml

Bumped `actions/upload-artifact` and `actions/download-artifact` versions from 3 to 4
The v3 for both of these actions has been deprecated, bumped them to v4
n/a
n/a
n/a

Bump Deprecated Workflow Functions

---

CHANGELOG.md
dbt/include/dremio/macros/materializations/incremental/incremental.sql
tests/functional/adapter/basic/test_incremental.py

This fixes the on_schema_change config
- Moves the `raw_on_schema_change` variable back into scope for the config validator
Reproduced the bug described in #268, made changes to a local version of `dbt-dremio` and confirmed that it was behaving as expected.
resolves: #268

fix: Issue with on_schema_change config

---

CHANGELOG.md
dbt/include/dremio/macros/materializations/helpers.sql

When using `partition_by`, dbt-dremio could be causing invalid statements to partition columns, surrounding the way quotation was being handled.
The sistematic double quoting has been removed from the connector's logic, stopping such situations from happening and leaving quotation to be decided by the user. An example of a table materialization under this new logic is:
```
{{
config(
materialized = 'table',
partition_by = ['forecast_effective_date', 'year("datetime_utc")', 'month("datetime_hour_ending_utc")']
)
}}
```
n/a
-   [X] Added a summary of what this PR accomplishes to CHANGELOG.md
-   [X] Please make sure you have signed our [Contributor License Agreement](https://www.dremio.com/legal/contributor-agreement/), which enables Dremio to distribute your contribution without …

Fix Invalid Quoting Around Partitioning

---

README.md
dbt/adapters/dremio/__version__.py
setup.py

Updates in the code for new release 1.8.2

new release 1.8.2

---

CHANGELOG.md
dbt/adapters/dremio/connections.py

Adding check if catalog/space already exists. It will unblock non-admin users in DC from starting to use dbt-dremio. 
Before only ADMIN users of DC were able to run dbt-dremio. Now we are checking if the catalog exists and it unblocks customers to use non-admin users in DC with dbt-dremio.
Created a tech dept ticket to create dbt-dremio tests for it. Run only manual tests with DC instance.

Adding new check if the space already exists

---

CHANGELOG.md
dbt/adapters/dremio/connections.py

We are trying to understand the adoption and distribution of dbt-dremio from DC usage data, therefore, we are including an additional value in query metadata that represents the version of dbt-dremio adapter.
Metadata before changes: `/* {"app": "dbt", "dbt_version": "1.8.8", "profile_name": <profile_name>, "target_name": <target_name>, ... } */`
Metadata after changes: `/* {"app": "dbt", "dbt_version": "1.8.8", "dbt_dremio_version": "1.8.3", "profile_name": <profile_name>, "target_name": <target_name>, ... } */`
- Created a new macro `DREMIO_QUERY_COMMENT`, which includes the dbt-dremio's version, to replace the default query comment `DEFAULT_QUERY_COMMENT` macro
- Created a new class `DremioMacroQueryStringSetter` that inherits `MacroQueryStringSetter` to override the method that …

Include dbt-dremio version in query metadata

---

CHANGELOG.md
dbt/adapters/dremio/__version__.py
dbt/include/dremio/macros/adapters/snapshot.sql
dbt/include/dremio/macros/builtins/builtins.sql
dev_requirements.txt
setup.py
tests/functional/adapter/empty/test_empty.py
tests/functional/adapter/materialization/fixtures.py
tests/functional/adapter/materialization/test_snapshots.py
tests/hooks/test_run_hooks.py

Updating dbt-dremio to match dbt-core v1.9.0.
Following [Adapter Maintainers: Upgrading to dbt-core v1.9.0](https://github.com/dbt-labs/dbt-core/discussions/11125):
- Snapshot improvements
- Snapshots: Enable setting a datetime value for `dbt_valid_to` for current records instead of `NULL`
- Snapshots: Enable `hard_deletes` config to add a metadata column if a record has been deleted (automatically inherited from dbt-adapters)
- Snapshots: Allow customizing names of metadata fields
- Snapshots: Enable `unique_key` as a list (automatically inherited from dbt-adapters)
- Microbatch incremental strategy → optional, so not included in this PR
- Fixed _tests/hooks/test_run_hooks.py_
- Added `TestSnapshotDbtValidToCurrentDremio`, `TestSnapshotColumnNamesDremio`, …

dbt 1.9 migration

---

CHANGELOG.md
dbt/adapters/dremio/credentials.py
dbt/include/dremio/macros/materializations/clone.sql
dbt/include/dremio/macros/materializations/twin_strategy.sql
dbt/include/dremio/profile_template.yml

Ability to run dbt against Dremio Enterprise Catalogs
With these changes, we give the users the possibility to choose whether to use **Enterprise Catalog** (EC) or **Space & Source** (S&S) as storage. Internally, using EC just means to have `datalake + root_path` (used for tables storage) and `database + schema` (used for views storage) with the EC path:
- Restructured `dbt init` prompt by introducing new project profile configuration options `enterprise_catalog_namespace` and `enterprise_catalog_folder`, so it's more intuitive for the users
- Disabled twin strategy when an Enterprise Catalog is being used (i.e., when `datalake + root_path` == `database + schema`)
- All CE tests pass

Support Dremio Enterprise Catalogs
